# Generated by Django 4.2.2 on 2024-05-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
